# fly.toml app configuration file generated for pixel-blocks-client on 2024-05-12T17:53:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pixel-blocks-client'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


[env]
  NEXT_PUBLIC_SERVER_COMPILE_URL = "https://pixel-blocks-server.fly.dev/compile"
  COMPILE_URL = "https://pixel-blocks-server.fly.dev/compile"
