FROM python:3.11

WORKDIR /server

ADD . .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

EXPOSE 8000

CMD ["python", "./main.py"]

